# Generated by Django 3.0.8 on 2021-02-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutRipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_types', models.CharField(choices=[('web', 'WEB'), ('logo', 'LOGO')], max_length=100)),
                ('faq_title', models.CharField(max_length=500)),
                ('faq_ans', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='GetStarted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_tagline', models.CharField(max_length=200)),
                ('card_desc', models.TextField()),
                ('card_btn', models.CharField(max_length=100)),
                ('title_color', models.CharField(max_length=100)),
                ('btn_color', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndexImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KindOfCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('web', 'WEB'), ('logo', 'LOGO')], max_length=70)),
                ('logo_icon', models.CharField(max_length=100)),
                ('card_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('web', 'WEB'), ('logo', 'LOGO')], max_length=100)),
                ('plan_title', models.CharField(max_length=100)),
                ('plan_price', models.CharField(max_length=100)),
                ('plan_tagline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WhyRipeChilli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=70)),
                ('Title', models.CharField(max_length=70)),
                ('Desc', models.TextField()),
            ],
        ),
    ]
