# Generated by Django 3.0.8 on 2021-02-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripechilliapp', '0002_websamples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('pin_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('proffesion', models.CharField(choices=[('marketing', 'MARKETING'), ('graphics', 'GRAPHICS DESIGNER'), ('webdeveloper', 'WEB DEVELOPER')], max_length=100)),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
            ],
        ),
    ]
