# Generated by Django 3.0.8 on 2021-02-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripechilliapp', '0003_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='proffesion',
            field=models.CharField(choices=[('MARKETING', 'MARKETING'), ('GRAPHICS DESIGNER', 'GRAPHICS DESIGNER'), ('WEB DEVELOPER', 'WEB DEVELOPER')], default='', max_length=100),
        ),
    ]
